jaffle_shop:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: admin
      password: admin
      port: 5432
      dbname: jaffle_shop
      schema: dbt
      threads: 4